Francisco-Villanueva/box-client

README.md
=> fix(readme): link to Dario Beratti LinkedIn profile fixed

src/commons/Checkbox.tsx, src/commons/index.ts
=> feat: created index.ts to root commons files

src/commons/Status.tsx
=> fix: update on StatusString

src/app/carrier/map/page.tsx, src/components/DeliveryInProgress.tsx
DeliveryInProgress component edited: <AppLayout> deleted
=> Carrier-map-route-view created

src/app/carrier/packages/page.tsx
=> fix: overflow & height on BoxLayout

src/app/admin/packages/create/page.tsx, src/app/login/page.tsx, src/commons/InputCalendar.tsx, src/commons/index.ts, src/components/Login.tsx
=> feat(client): login a new packages view

src/app/admin/packages/page.tsx
=> fix: admin packages view modified

src/app/carrier/map/page.tsx, src/components/DeliveryInProgress.tsx
Button functions: "Reparto en Curso" & "Finalizar" return to /carrier home
=> fix(DeliveryInProgress): Props added with package data

src/app/admin/packages/page.tsx
Reverts BrianBts/box-client#61
=> Revert "fix: fix button for trimmer in /admin/packages"

src/components/ShipmentCard.tsx, src/models/user.store.ts
Created a filter function to delete packages from history & pending lists.
=> feat (packages): delete package functionallity

src/app/admin/packages/page.tsx, src/app/admin/page.tsx, src/commons/Status.tsx, src/components/DetailCard.tsx, src/models/date.store.ts
en la vista de  admin/pacakges, implemente el uso de la view  `packagesByDate` para ver los filtrar los paquetes segun la fecha.
Filtro los todos los paquetes `packages` y los paquetes entregados `deliverdPackages`
=> feat (date packages): setting rigth packages with date of details

gitflow-semver.md, src/commons/GoogleMap.tsx, src/commons/Icons.tsx, src/components/DeliveryInProgress.tsx
Icon.tsx common edited: "onClick" prop added to IconProps.
DeliveryInProgress.tsx component edited: "useRouter" imported. <ArrowLeft onClick={() => router.back()} /> (<Link> replaced)
=> fix(client):Geolocation implemented in GoogleMap common.

gitflow-semver.md, package-lock.json, package.json, src/app/Providers.tsx, src/models/packages.store.ts, src/models/root.store.ts, src/models/user.store.ts, src/services/package.services.ts, src/services/user.services.ts
- I created servicies files to consume json data.
- Fix some lines and delete "any" en Packages/User.
- I modify some files that had wrong name.
- I installed axios dependencies that we will use.
=> feat(client): add services and consume json data

src/components/Login.tsx, src/services/index.ts
=> fix(login):Disabled user receives error message and can not login

src/app/carrier/packages/page.tsx, src/app/page.tsx, src/components/RegisterForm.tsx, src/components/ShipmentCard.tsx
=> Feat(client): "/" redirects to "/login"

src/app/admin/packages/create/page.tsx, src/commons/Input.tsx, src/components/FormInput.tsx, src/components/Login.tsx, src/components/RegisterForm.tsx, src/components/index.ts, src/hooks/useInput.ts, tailwind.config.ts
Cree un compomente FormInput en el cual se usa el hook "useInput" y el common "Input". Entonces cada vez que se quiera usar un input, hay que usar el <FormInput  />.
Implementacion en el Login:
Definicion del  FormInput:
Validaciones dentro del useInput con los metodos onBlur y onFocus:
=> feat (useInput): add validation inputs

src/app/admin/packages/create/page.tsx, src/commons/Input.tsx, src/components/Login.tsx, src/components/RegisterForm.tsx, src/hooks/useInput.ts
Se agrego:
- Validacion para el input con type name.
- Correccion de classname y ubicacion de los msj de alerta.
- Modificacion de placeholders y alertas de ingles a castellano en el Login y Register.
=> fix: input error/validation in Login & Register

src/app/loading.tsx
=> feat(client): Loading spinner created

.github/workflows/pipeline.yml
add build step to git hub actions
=> feat (actions): add build steps

src/app/admin/packages/create/page.tsx, src/hooks/useInput.ts
=> fix (client): create package´s form validations

src/app/admin/packages/create/page.tsx, src/components/RegisterForm.tsx, src/hooks/useInput.ts
=> feat: username input in register form

src/commons/Icons.tsx, src/components/RegisterForm.tsx
Al hacer click en el ícono de la cámara se muestra un input. Se pega la url de la imagen dentro del input y ésta se muestra en lugar del ícono. Al presionar "Enter" dentro del input (o al hacer click en la imagen), éste desaparece. Si se desea cambiar la url, haciendo click sobre la imagen se vuelve a mostrar el input.
[Grabación de pantalla desde 29-11-23 14:11:47.webm](https://github.com/BrianBts/box-client/assets/137564078/170d1707-9db5-43de-86ad-14e273001059)
=> Feat: Profile Image

src/app/admin/packages/create/page.tsx, src/commons/Input.tsx
Input de tipo fecha en formulario de "Crear Paquete" controlado.
En lugar de usar el common "InputCalendar", use el FormInput con su type y classname particular para manejar el input de igual manera que el resto.
=> fix(client): date input in create package form controlled

src/components/Login.tsx, src/models/user.store.ts, src/services/auth.services.ts, src/services/index.ts, src/services/package.services.ts, src/services/user.services.ts, src/types/user.types.ts
- Se agregó la logica de **login** pero sin usar FormInput y se estructuró las validaciones. (Chequear)
- Se implemento _findUserByUserName_ en user.store para buscar por userName
- Se inyecto data del back desde los servicios. (Quedaron dos console logs para chequear porque trae la info 2 veces)
- Se typo con maybe la image en user.types para que reciba undefined o null si el usuario no carga una foto.
-
=> feat(login): add logic login and add common input

src/app/admin/carriers/profile/page.tsx, src/commons/Switch.tsx, src/components/CarrierStatusCard.tsx
El componente CarrierStatusCard no se estaba usando. Lo agregué al page.tsx de admin/carriers/profile.
El Switch recibe el status para mostrarse activo o no; falta aplicar la logica para actualizar el estado del usuario.
=> fix: Carrier status card component in /admin/carriers/profile

src/components/CarrierStatusCard.tsx
Se arreglo bug de renderizado al cambiar el status de un carrier (switch y estado)
=> fix:switch and carrier status correctly rendering

package-lock.json, package.json, src/components/RegisterForm.tsx, src/services/auth.services.ts
Se creó el servicio para enviar la imagen al back:
Se modificó el componente RegisterForm:
Se desinstalaron las dependencias de aws en el front:
=> fix(client):AWS S3 service moved to API

src/app/admin/carriers/profile/page.tsx, src/commons/CarrierStatus.tsx, src/components/CarrierStatusCard.tsx
El container del estado del carrier mantiene su tamaño al cambiar
=> fix: carriers status box

src/components/ShipmentCard.tsx, src/components/ShipmentView.tsx, src/models/user.store.ts
En la ruta /admin/carriers/profile se renderizan los packetes del carrier seleccionado, antes solo se renderizaban los paquetes del usuario logueado
=> fix: /admin/carriers/profile renders selected user packages

src/components/DeliveryInProgress.tsx
Funcionalidad al boton de Cancelar Entrega
=> fix: Cancel delivery button

src/app/carrier/sworn-statement/page.tsx, src/commons/SwornStatementBox.tsx, src/components/DeliveryInProgress.tsx
Se Agregó un botón "CAMBIAR RESPUESTA" en cada pregunta de la declaración jurada. Las respuestas se pueden cambiar de forma individual, o borrar todas las respuestas a la vez:
https://github.com/Francisco-Villanueva/box-client/assets/137564078/2c72b402-9ac5-492e-9e89-39b104fca404
Se agregó el spinner en el mapa para que no muestre el error de Google Maps:
Tambíen se agregó "Cargando..." a los datos del paquete
https://github.com/Francisco-Villanueva/box-client/assets/137564078/e247dd03-0a55-4599-8c43-d420f9a755cf
=> fix(sworn-statement): Answers can be changed individually

src/app/carrier/sworn-statement/page.tsx, src/components/CarrierStatusCard.tsx, src/components/Login.tsx, src/services/user.services.ts, src/types/user.types.ts, src/utils/index.ts, src/utils/timeZoneSetter.ts
Despues de 24hs (expresado en milisegundos), el usuario rechazado se loguea y vuelve a estar con status "HABILITADO"
=> feat: Enable user after 24hs of rejected

src/models/date.store.ts
Se arreglo el formato en las fechas de Mobx para corregir los filtros por fechas de paquetes
=> fix: Fixed dates format in mobx

src/commons/GoogleMap.tsx
Se sacó la api key del common y se la agregó como variable de entorno
=> fix(GoogleMap Commmon): GOOGLE_API_KEY

src/app/admin/packages/create/page.tsx, src/app/admin/packages/page.tsx, src/components/CarrierStatusCard.tsx, src/components/ShipmentCard.tsx, src/components/ShipmentView.tsx, src/types/packages.types.ts
Desasignar los paquetes pendientes y en curso de los carriers (tanto admin como carrier)
Borrar del historial los paquetes entregados (Admin y carrier ven historiales distintos)
=> feat: delete delivered packages from history

jest.config.ts, jest.setup.ts, package-lock.json, package.json, src/commons/__test__/AppLayout.test.tsx, src/commons/__test__/BoxLayout.test.tsx, src/commons/__test__/BoxTitle.test.tsx, src/commons/__test__/Button.test.tsx, src/commons/__test__/Title.test.tsx, src/commons/__test__/UserImg.test.tsx, src/components/__test__/Login.test.tsx
Se configuró Jest y React Testing Library para testeo de componentes. Se crearon 18 tests.... falta completar
=> feat(client): Component Testing

src/components/ResetPasswordView.tsx
Baje el message succes y push despues del servicio de resetPassword.
Haciendo pruebas, me salia el alerta de mensaje exitoso pero el servicio fallaba.
=> fix(CLIENT): ResetPasswordView update on success message

src/app/admin/carriers/page.tsx, src/app/admin/packages/page.tsx, src/components/ShipmentCard.tsx
-Se cambio el mensaje al archivar un paquete
-Se agrego un loader para que no renderice una fecha incorrecta al hacer refresh
=> fix: Add loader in dates

src/app/admin/packages/page.tsx, src/app/login/page.tsx
-Vista de login chequea si hay datos de usuario en LS, y redirecciona (al cerrar el browser y volver a abrir)
=> fix: login view redirects if there is a token in localstorage
